# Generated by Django 4.1.3 on 2023-03-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0002_location_parcel_status_alter_travel_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
