# Generated by Django 4.1.3 on 2023-04-12 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parcels', '0003_alter_parcel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('successor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parcels.city')),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(blank=True, default='', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RideCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateField(default=django.utils.timezone.now)),
                ('departure_date', models.DateField(default=django.utils.timezone.now)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcels.city')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcels.ride')),
                ('successor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parcels.ridecity')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='travel',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='start_location',
        ),
        migrations.RenameField(
            model_name='parcel',
            old_name='delivery_address',
            new_name='recipient',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='tracking_number',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='travel',
        ),
        migrations.AddField(
            model_name='parcel',
            name='sender',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Travel',
        ),
        migrations.AddField(
            model_name='parcel',
            name='dropoff_city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dropoff_parcel', to='parcels.city'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='pickup_city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_parcel', to='parcels.city'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='ride',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ride_parcel', to='parcels.ride'),
        ),
    ]
