# Generated by Django 4.1.3 on 2023-04-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0004_city_ride_ridecity_userprofile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ridecity',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='city',
            name='successor',
        ),
        migrations.RemoveField(
            model_name='ridecity',
            name='arrival_date',
        ),
        migrations.RemoveField(
            model_name='ridecity',
            name='departure_date',
        ),
        migrations.RemoveField(
            model_name='ridecity',
            name='successor',
        ),
        migrations.AddField(
            model_name='ride',
            name='cities',
            field=models.ManyToManyField(through='parcels.RideCity', to='parcels.city'),
        ),
        migrations.AddField(
            model_name='ridecity',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
