# Generated by Django 4.1.3 on 2023-04-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0005_alter_ridecity_options_remove_city_successor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='destination',
            field=models.CharField(choices=[('PL', 'Poland'), ('GE', 'Georgia')], default='PL', max_length=2),
        ),
    ]
