# Generated by Django 4.1.3 on 2023-04-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0007_alter_ride_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='destination',
            field=models.CharField(choices=[('Poland', 'Poland'), ('Georgia', 'Georgia')], default='PL', max_length=16),
        ),
    ]
